@extends('adminlte::page')

@section('title', $title ?? 'Report Details')

@section('content_header')
<div class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="mb-0">{{ $title ?? 'Report Details' }}</h1>

        @if(isset($breadcrumb))
            <ol class="breadcrumb mt-2 mb-0 bg-transparent p-0">
                @foreach($breadcrumb as $item)
                    <li class="breadcrumb-item">
                        <a href="{{ $item['url'] }}">{{ $item['text'] }}</a>
                    </li>
                @endforeach
            </ol>
        @endif
    </div>

    <div>
        @if ($report->file_path)
            <a href="{{ route('admin.reports.download', $report->id) }}" class="btn btn-success">
                <i class="fas fa-download mr-1"></i> Download
            </a>
        @endif

        <a href="{{ route('admin.reports.index') }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left mr-1"></i> Back
        </a>
    </div>
</div>
@endsection

@section('content')

<div class="row">
    <div class="col-md-8">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 font-weight-bold">
                    <i class="fas fa-info-circle text-primary mr-1"></i>
                    Report Information
                </h5>
            </div>

            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th style="width: 220px;">Report UID</th>
                        <td><code>{{ $report->report_uid }}</code></td>
                    </tr>

                    <tr>
                        <th>Title</th>
                        <td>{{ $report->title }}</td>
                    </tr>

                    <tr>
                        <th>Report Type</th>
                        <td>
                            <span class="badge badge-info">
                                {{ $reportTypes[$report->report_type] ?? $report->report_type }}
                            </span>
                        </td>
                    </tr>

                    <tr>
                        <th>Date Range</th>
                        <td>
                            {{ optional($report->date_from)->format('d M Y') ?? 'Start' }}
                            -
                            {{ optional($report->date_to)->format('d M Y') ?? 'Today' }}
                        </td>
                    </tr>

                    <tr>
                        <th>Group By</th>
                        <td>{{ $report->group_by ?? 'N/A' }}</td>
                    </tr>

                    <tr>
                        <th>Format</th>
                        <td>
                            @if ($report->format === 'csv')
                                <span class="badge badge-success">CSV</span>
                            @elseif ($report->format === 'pdf')
                                <span class="badge badge-danger">PDF</span>
                            @elseif ($report->format === 'excel')
                                <span class="badge badge-primary">Excel</span>
                            @else
                                <span class="badge badge-secondary">HTML</span>
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <th>Status</th>
                        <td>
                            @if ($report->status === 'completed')
                                <span class="badge badge-success">Completed</span>
                            @elseif ($report->status === 'processing')
                                <span class="badge badge-warning">Processing</span>
                            @elseif ($report->status === 'failed')
                                <span class="badge badge-danger">Failed</span>
                            @else
                                <span class="badge badge-secondary">{{ ucfirst($report->status) }}</span>
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <th>Generated By</th>
                        <td>{{ optional($report->generatedBy)->name ?? 'System' }}</td>
                    </tr>

                    <tr>
                        <th>Generated At</th>
                        <td>{{ optional($report->generated_at)->format('d M Y, h:i A') ?? 'N/A' }}</td>
                    </tr>
                </table>

                @if ($report->error_message)
                    <div class="alert alert-danger">
                        <strong>Error:</strong> {{ $report->error_message }}
                    </div>
                @endif
            </div>
        </div>

        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 font-weight-bold">
                    <i class="fas fa-calculator text-success mr-1"></i>
                    Report Summary
                </h5>
            </div>

            <div class="card-body">
                @if (! empty($report->summary))
                    <div class="row">
                        @foreach ($report->summary as $key => $value)
                            <div class="col-md-4 col-sm-6 mb-3">
                                <div class="summary-card">
                                    <small class="text-muted text-uppercase">
                                        {{ str_replace('_', ' ', $key) }}
                                    </small>

                                    <h5 class="mb-0 mt-1">
                                        @if (is_array($value) || is_object($value))
                                            {{ json_encode($value) }}
                                        @elseif (is_numeric($value))
                                            {{ number_format($value) }}
                                        @else
                                            {{ $value }}
                                        @endif
                                    </h5>
                                </div>
                            </div>
                        @endforeach
                    </div>
                @else
                    <p class="text-muted mb-0">No summary data available.</p>
                @endif
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 font-weight-bold">
                    <i class="fas fa-file text-primary mr-1"></i>
                    File Information
                </h5>
            </div>

            <div class="card-body">
                <p>
                    <strong>File Name:</strong><br>
                    {{ $report->file_name ?? 'N/A' }}
                </p>

                <p>
                    <strong>File Path:</strong><br>
                    {{ $report->file_path ?? 'N/A' }}
                </p>

                <p>
                    <strong>Disk:</strong><br>
                    {{ $report->file_disk ?? 'public' }}
                </p>

                <p>
                    <strong>Mime Type:</strong><br>
                    {{ $report->mime_type ?? 'N/A' }}
                </p>

                <p>
                    <strong>File Size:</strong><br>
                    @if ($report->file_size)
                        {{ number_format($report->file_size / 1024, 2) }} KB
                    @else
                        N/A
                    @endif
                </p>

                @if ($report->file_path)
                    <a href="{{ route('admin.reports.download', $report->id) }}" class="btn btn-success btn-block">
                        <i class="fas fa-download mr-1"></i> Download File
                    </a>
                @else
                    <div class="alert alert-warning mb-0">
                        File not generated. CSV format generates file now.
                    </div>
                @endif
            </div>
        </div>

        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 font-weight-bold">
                    <i class="fas fa-filter text-warning mr-1"></i>
                    Filters
                </h5>
            </div>

            <div class="card-body">
                @if (! empty($report->filters))
                    <ul class="list-group list-group-flush">
                        @foreach ($report->filters as $key => $value)
                            <li class="list-group-item px-0 d-flex justify-content-between">
                                <strong>{{ str_replace('_', ' ', $key) }}</strong>
                                <span>
                                    @if (is_array($value) || is_object($value))
                                        {{ json_encode($value) }}
                                    @else
                                        {{ $value ?: 'N/A' }}
                                    @endif
                                </span>
                            </li>
                        @endforeach
                    </ul>
                @else
                    <p class="text-muted mb-0">No filters applied.</p>
                @endif
            </div>
        </div>

        <div class="card border-0 shadow-sm">
            <div class="card-header bg-white">
                <h5 class="mb-0 font-weight-bold">
                    <i class="fas fa-columns text-info mr-1"></i>
                    Columns
                </h5>
            </div>

            <div class="card-body">
                @if (! empty($report->columns))
                    @foreach ($report->columns as $column)
                        <span class="badge badge-light border mb-1">
                            {{ str_replace('_', ' ', $column) }}
                        </span>
                    @endforeach
                @else
                    <p class="text-muted mb-0">No custom columns selected.</p>
                @endif
            </div>
        </div>
    </div>
</div>

@endsection

@section('css')
<style>
.breadcrumb-item+.breadcrumb-item::before {
    content: ">";
}

.summary-card {
    background: #f8fafc;
    border: 1px solid #e5e7eb;
    border-radius: 10px;
    padding: 15px;
    height: 100%;
}
</style>
@endsection