<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('report_exports', function (Blueprint $table) {
            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Basic Report Information
            |--------------------------------------------------------------------------
            */
            $table->string('report_uid')->unique();
            $table->string('title');
            $table->string('report_type')->index();

            /*
            |--------------------------------------------------------------------------
            | Report Date Range
            |--------------------------------------------------------------------------
            */
            $table->date('date_from')->nullable()->index();
            $table->date('date_to')->nullable()->index();

            /*
            |--------------------------------------------------------------------------
            | Report Grouping / Format
            |--------------------------------------------------------------------------
            */
            $table->string('group_by')->nullable();
            // daily, weekly, monthly, campaign, product, employee, status

            $table->string('format')->default('html');
            // html, pdf, excel, csv

            /*
            |--------------------------------------------------------------------------
            | Report Filters
            |--------------------------------------------------------------------------
            | Example:
            | campaign_id, product_id, employee_id, order_status,
            | payment_status, delivery_area, is_fake
            |--------------------------------------------------------------------------
            */
            $table->json('filters')->nullable();

            /*
            |--------------------------------------------------------------------------
            | Report Columns
            |--------------------------------------------------------------------------
            | Example:
            | customer_name, phone, total_amount, order_status
            |--------------------------------------------------------------------------
            */
            $table->json('columns')->nullable();

            /*
            |--------------------------------------------------------------------------
            | Report Summary Data
            |--------------------------------------------------------------------------
            | Example:
            | total_orders, total_sales, pending_orders, delivered_orders
            |--------------------------------------------------------------------------
            */
            $table->json('summary')->nullable();

            /*
            |--------------------------------------------------------------------------
            | Exported File Information
            |--------------------------------------------------------------------------
            */
            $table->string('file_name')->nullable();
            $table->string('file_path')->nullable();
            $table->string('file_disk')->default('public');
            $table->string('mime_type')->nullable();
            $table->unsignedBigInteger('file_size')->nullable();

            /*
            |--------------------------------------------------------------------------
            | Report Status
            |--------------------------------------------------------------------------
            */
            $table->string('status')->default('completed')->index();
            // pending, processing, completed, failed

            $table->text('error_message')->nullable();

            /*
            |--------------------------------------------------------------------------
            | Generated By
            |--------------------------------------------------------------------------
            */
            $table->foreignId('generated_by')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            $table->timestamp('generated_at')->nullable();

            $table->timestamps();
            $table->softDeletes();

            /*
            |--------------------------------------------------------------------------
            | Indexes
            |--------------------------------------------------------------------------
            */
            $table->index(['report_type', 'status']);
            $table->index(['date_from', 'date_to']);
            $table->index(['generated_by', 'report_type']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('report_exports');
    }
};