<div class="table-responsive">
    <table class="table table-hover mb-0">
        <thead class="thead-light">
            <tr>
                <th style="width: 45px;">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="check_all">
                        <label class="custom-control-label" for="check_all"></label>
                    </div>
                </th>
                <th style="width: 70px;">SL</th>
                <th>Report UID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Format</th>
                <th>Status</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th style="width: 270px;">Action</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($reports as $report)
                <tr>
                    <td>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox"
                                   class="custom-control-input row-checkbox"
                                   id="report_check_{{ $report->id }}"
                                   value="{{ $report->id }}">
                            <label class="custom-control-label" for="report_check_{{ $report->id }}"></label>
                        </div>
                    </td>

                    <td>{{ $reports->firstItem() + $loop->index }}</td>

                    <td>
                        <code>{{ $report->report_uid }}</code>
                    </td>

                    <td>
                        <div class="report-title-limit">
                            <strong>{{ $report->title }}</strong>
                        </div>
                    </td>

                    <td>
                        <span class="badge badge-info">
                            {{ $reportTypes[$report->report_type] ?? $report->report_type }}
                        </span>
                    </td>

                    <td>
                        @if ($report->format === 'csv')
                            <span class="badge badge-success">
                                <i class="fas fa-file-csv mr-1"></i> CSV
                            </span>
                        @elseif ($report->format === 'pdf')
                            <span class="badge badge-danger">
                                <i class="fas fa-file-pdf mr-1"></i> PDF
                            </span>
                        @elseif ($report->format === 'excel')
                            <span class="badge badge-primary">
                                <i class="fas fa-file-excel mr-1"></i> Excel
                            </span>
                        @else
                            <span class="badge badge-secondary">
                                <i class="fas fa-file-alt mr-1"></i> HTML
                            </span>
                        @endif
                    </td>

                    <td>
                        @if ($report->status === 'completed')
                            <span class="badge badge-success">Completed</span>
                        @elseif ($report->status === 'processing')
                            <span class="badge badge-warning">Processing</span>
                        @elseif ($report->status === 'failed')
                            <span class="badge badge-danger">Failed</span>
                        @else
                            <span class="badge badge-secondary">{{ ucfirst($report->status) }}</span>
                        @endif
                    </td>

                    <td>
                        {{ optional($report->generatedBy)->name ?? 'System' }}
                    </td>

                    <td>
                        {{ optional($report->generated_at)->format('d M Y, h:i A') ?? 'N/A' }}
                    </td>

                    <td>
                        @if (! $isTrash)
                            <a href="{{ route('admin.reports.show', $report->id) }}"
                               class="btn btn-sm btn-dark"
                               title="Details">
                                <i class="fas fa-eye"></i>
                            </a>

                            <a href="{{ route('admin.reports.edit', $report->id) }}"
                               class="btn btn-sm btn-info"
                               title="Edit">
                                <i class="fas fa-edit"></i>
                            </a>

                            @if ($report->file_path)
                                <a href="{{ route('admin.reports.download', $report->id) }}"
                                   class="btn btn-sm btn-success"
                                   title="Download">
                                    <i class="fas fa-download"></i>
                                </a>
                            @endif

                            <button type="button"
                                    class="btn btn-sm btn-danger btnDelete"
                                    data-url="{{ route('admin.reports.destroy', $report->id) }}"
                                    title="Move to Trash">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        @else
                            <button type="button"
                                    class="btn btn-sm btn-success btnRestore"
                                    data-url="{{ route('admin.reports.restore', $report->id) }}"
                                    title="Restore">
                                <i class="fas fa-trash-restore"></i>
                            </button>

                            <button type="button"
                                    class="btn btn-sm btn-danger btnForceDelete"
                                    data-url="{{ route('admin.reports.force_delete', $report->id) }}"
                                    title="Purge Permanently">
                                <i class="fas fa-times"></i>
                            </button>
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="text-center text-muted py-4">
                        No reports found.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>

@if ($reports->hasPages())
    <div class="px-4 py-3 border-top bg-white">
        {{ $reports->withQueryString()->links() }}
    </div>
@endif